package com.feros.api.enums;

public enum NotificationType {
    SUBSCRIPTION_EXPIRY,
    TRIAL_ENDING,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_SUSPENDED,
    BROADCAST,
    SYSTEM,
    TYRE_FITTED,
    TYRE_ROTATION,
    TYRE_EXPIRY,
    TYRE_ROTATION_DUE
}
