-- Vehicle body types — Indian transport industry standard classification.
-- Safe to run multiple times — INSERT IGNORE skips duplicates on `name`.
INSERT IGNORE INTO vehicle_body_types (name, is_active, created_at, updated_at) VALUES
('DCM',                   1, NOW(), NOW()),
('LCV',                   1, NOW(), NOW()),
('SCV',                   1, NOW(), NOW()),
('ICV',                   1, NOW(), NOW()),
('MCV',                   1, NOW(), NOW()),
('HCV',                   1, NOW(), NOW()),
('Tipper',                1, NOW(), NOW()),
('Trailer',               1, NOW(), NOW()),
('Semi-Trailer',          1, NOW(), NOW()),
('Flatbed',               1, NOW(), NOW()),
('Container',             1, NOW(), NOW()),
('Refrigerated Container',1, NOW(), NOW()),
('Closed Body',           1, NOW(), NOW()),
('Open Body',             1, NOW(), NOW()),
('Pick-Up',               1, NOW(), NOW()),
('Mini Truck',            1, NOW(), NOW()),
('Tanker',                1, NOW(), NOW()),
('Fuel Tanker',           1, NOW(), NOW()),
('Water Tanker',          1, NOW(), NOW()),
('Milk Tanker',           1, NOW(), NOW()),
('Chemical Tanker',       1, NOW(), NOW()),
('LPG Tanker',            1, NOW(), NOW()),
('CNG Tanker',            1, NOW(), NOW()),
('Powder Tanker',         1, NOW(), NOW()),
('Bulker',                1, NOW(), NOW()),
('Dumper',                1, NOW(), NOW()),
('Lowbed',                1, NOW(), NOW()),
('Car Carrier',           1, NOW(), NOW()),
('Cattle Carrier',        1, NOW(), NOW()),
('Timber Carrier',        1, NOW(), NOW()),
('Concrete Mixer',        1, NOW(), NOW()),
('Transit Mixer',         1, NOW(), NOW()),
('Compactor',             1, NOW(), NOW()),
('Garbage Truck',         1, NOW(), NOW()),
('Crane',                 1, NOW(), NOW()),
('Multi-Axle',            1, NOW(), NOW()),
('Bus',                   1, NOW(), NOW()),
('Mini Bus',              1, NOW(), NOW()),
('School Bus',            1, NOW(), NOW()),
('Staff Bus',             1, NOW(), NOW()),
('Ambulance',             1, NOW(), NOW()),
('Covered Van',           1, NOW(), NOW()),
('Tow Truck',             1, NOW(), NOW()),
('Fire Truck',            1, NOW(), NOW()),
('Tractor',               1, NOW(), NOW());
